### ISSUE TITLE
Cycle lane track colour field colours whole road 

### ISSUE THREAD

**Issue by RobJN** [cyclestreets/tflcid-conversion#10]
As currently proposed surface:colour=blue on a cycle lane might be interpreted to mean the whole road. Why?

- highway=residential
- cycleway=lane
- surface:colour=blue

Perhaps cycleway:lane:colour=* instead (matches the existing cycleway:lane:width=* tag). The surface:colour=* tag would be ok on a highway=cycleway.

**Comment by RobJN** [comment]
Hold on. Sometimes this will be the colour of a shared bus lane right? If so you will have an existing osm tag such as cycleway:left=share_busway. In which case the colour should be cycleway:left:colour=*.

**Comment by matkoniecz** [comment]
`cycleway:surface:color`?

**Comment by mvl22** [comment]
> cycleway:surface:color

Yes, I agree, that is what should be used.

[Taginfo shows](https://taginfo.openstreetmap.org/keys/?key=cycleway:surface:colour#values) this is indeed in use.

> cycleway:left=share_busway. In which case the colour should be cycleway:left:colour

Yes, correct that we should add the :left / :right if that is what we are attaching to.

@systemed [Looks as if](https://github.com/cyclestreets/tflcid-conversion/blob/master/preparation/clt_to_postgis.rb#L20) we didn't implement `CLT_COLOUR`, presumably hence this ticket. Action is:

- If `CLT_COLOUR` present, map the value directly to `cycleway:surface:colour`. If the cycleway is actually cycleway:left or cycleway:right, use `cycleway:left:surface:colour` / `cycleway:right:surface:colour` obviously.

Looks as if this will need a schema change to add that field, judging from the [current table definition](https://github.com/cyclestreets/tflcid-conversion/blob/master/preparation/clt_to_postgis.rb#L20).

**Comment by systemed** [comment]
The lingua franca of OSM is British English, so `cycleway:surface:colour` of course ;)

**Comment by mvl22** [comment]
Apologies, yes, of course. Comes of having coded CSS earlier in the day :) I've edited the above post to avoid any confusion or copy-and-paste issues.

Also fixed in schema documentation in pull request #9.
