### ISSUE TITLE
Side-road entry treatment

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/tflcid-conversion#16]
Suggestion from Jez C:
https://lists.openstreetmap.org/pipermail/talk-gb/2019-September/023514.html

"• Side-road entry treatment:

The `sidewalk=yes` tag is already in use as an attribute of `highway=*` when it is not known which side(s) of a street has sidewalks.

I would tag this node as `highway=crossing` and `traffic_calming=table`. 

If the adjacent highway already has `cycleway:sideroad_continuity=yes` I'm not convinced why you need a `continuous=yes` tag on the crossing node as well especially as there appears to be `tactile_paving` on the example photo too. 

Is there something special about these crossings that vehicles/cyclists turning into/out of the side-road must give way to pedestrians?"

**Comment by mvl22** [comment]
Richard Fairhurst wrote in:
https://lists.openstreetmap.org/pipermail/talk-gb/2019-September/023522.html

> A new tag cycleway:sideroad_continuity=yes is proposed as a backwards-compatible addition that elaborates on cycleway={lane|track}.

"Good concept but the tag is a little wordy. I wonder if a simple node at the junction tagged with "priority=cycleway" would be less verbose, and also permit "priority=road" for those situations where the sideroad has priority (this is sadly probably implicit, but it's good to tag out ambiguity)."

**Comment by systemed** [comment]
Thread at https://lists.openstreetmap.org/pipermail/tagging/2020-January/050557.html (also #30)

**Comment by mvl22** [comment]
Merging the comments above into #38 as these all relate to the same thing.

**Comment by mvl22** [comment]
Merging the comments above into #38 as these all relate to the same thing.
