### ISSUE TITLE
Stands, "M stands" and "P stands"

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/tflcid-conversion#18]
Rob Nickerson wrote in:
https://lists.openstreetmap.org/pipermail/talk-gb/2019-September/023516.html

"You suggest "bicycle_parking=stands" for 3 cases of the TfL data: Stands, "M stands" and "P stands". I shall let others comment on whether we want to introduce new OSM tags for these. Perhaps cyclists have an interest if one is preferable to another. (See: https://bikedata.cyclestreets.net/tflcid/conversion/#prk_mstand )"

**Comment by mvl22** [comment]
Richard Fairhurst wrote in:
https://lists.openstreetmap.org/pipermail/talk-gb/2019-September/023522.html

> • Bicycle parking stand types: The CID has several variations on the Sheffield stand [...] downstream users of the data would not consider the difference important – they simply care mostly whether the frame is lockable or not.

"It's perhaps a bit more nuanced than that - as a cyclist I find the type of stand has a big impact on whether it's lockable or not (around town I generally ride a Bike Friday New World Tourist, which has a weird little locking point, and use a mini D-lock; not all stands co-operate!). But I'd agree this isn't really a priority in any case."

**Comment by mvl22** [comment]
Currently the [code shows](https://github.com/cyclestreets/tflcid-conversion/blob/master/readers/parking.rb#L87-L89) that we map all of `PRK_SHEF`, `PRK_MSTAND`, `PRK_PSTAND` to `bicycle_parking=stands`.

The [wiki](https://wiki.openstreetmap.org/wiki/Key:bicycle_parking) has no further definition, and it would be a shame to lose the distinction here, but it is nonetheless a type of `stand`. We could add a note or do what is normally done with a sub-definition, namely use a coloned key.

@systemed Action here is:

- For `PRK_MSTAND`, keep the existing bicycle_parking=stands and add `bicycle_parking:stands=M stand`
- For `PRK_PSTAND`, keep the existing bicycle_parking=stands and add `bicycle_parking:stands=P stand`

**Comment by systemed** [comment]
Done but with `=m_stand` and `=p_stand`, which is more idiomatic OSM.

**Comment by mvl22** [comment]
Sorry, yes, agreed that is more correct.
