### ISSUE TITLE
Cycle parking - lockers

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/tflcid-conversion#19]
Rob Nickerson wrote in:
https://lists.openstreetmap.org/pipermail/talk-gb/2019-September/023516.html

"`bicycle_parking=locker` implies individual compartments for each bike. I was about to suggest that this doesn't therefore seem right for TfL's "hanger" (https://bikedata.cyclestreets.net/tflcid/conversion/#prk_hangar). Was going to suggest just `bicycle_parking=stands` + `covered=yes`. However a look at the images suggests that these are all from a single rental company and that they are secure spaces which you rent out (see https://cyclehoop.force.com/RentalsCommunity/resultsmap?postalCode=se1 ) given how many there are I am sure London mappers will already have come up with a tagging solution... Maybe just locker as you propose and not worrying about the fact that 6 bikes share a single locker. Shed seems to be the alternate option here."

**Comment by mvl22** [comment]
There was subsequent discussion on talk-gb on this:
https://lists.openstreetmap.org/pipermail/talk-gb/2021-February/026201.html

which recommends:

```
access=private
amenity=bicycle_parking
bicycle_parking=stands
covered=yes
operator=Cyclehoop Rentals
capacity=...
```

which looks correct to me.

[Overpass Turbo shows](https://overpass-turbo.eu/s/1kC6) this matches usage, though sometimes `bicycle_parking = shed` is used.

Looking at the [wiki page](url), shed does seem closer than lockers in this case, as lockers implies a single bicycle.

Currently the [code has](https://github.com/cyclestreets/tflcid-conversion/blob/master/readers/parking.rb#L94) just:

`if tfl['hangar'] then tags['bicycle_parking']='lockers' end`

@systemed So I think action here is to change that line to use those tags above, though I would change the type to `bicycle_parking=shed`.

**Comment by systemed** [comment]
Fixed in https://github.com/cyclestreets/tflcid-conversion/commit/40b022d7b53e4e80cc1d6fcdf2d678965f4fa373.
