### ISSUE TITLE
Bicycle early release traffic lights

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/tflcid-conversion#24]
Richard Fairhurst wrote in:
https://lists.openstreetmap.org/pipermail/talk-gb/2019-September/023522.html

> A new tag `traffic_signals:bicycle_early_release=yes` is proposed.

"Again, rather wordy, but I can't immediately think of a more concise alternative."

**Comment by mvl22** [comment]
As of 2022, the wiki now documents such a tag:
https://wiki.openstreetmap.org/wiki/Key:traffic_signals:bicycle_early_release

So this can be regarded as settled. [Taginfo shows](https://taginfo.openstreetmap.org/keys/?key=traffic_signals%3Abicycle_early_release#values) this is in use.

@systemed Action is:

Where `SIG_EARLY=TRUE`, set `traffic_signals:bicycle_early_release=yes`.

**Comment by systemed** [comment]
Note that we don't currently have a signal importer at all, so this is more than a trivial change. I can look at writing one in due course but I'll prioritise the other fixes above it.

**Comment by mvl22** [comment]
It's clear that this new type of signal has been of active interest in advocacy, resulting in its introduction. It is an important aspect in implementing the dutch principle of segregation by time/space for junctions. So I do think it's important it is put in. We've been starting to use this tag here in Cambridge, and is part of advocacy work.

Most of the other fixes you made good progress on, so if we could turn attention to this as soon as possible, that would be good.

**Comment by systemed** [comment]
Pencilled in for later this week!

**Comment by systemed** [comment]
New reader in https://github.com/cyclestreets/tflcid-conversion/commit/c8c476a1fa2f5dab2d3d21f46cba8fa669ce9ab2.
