### ISSUE TITLE
Bicycle dismount (UK 'cyclists dismount' sign)

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/tflcid-conversion#25]
Richard Fairhurst wrote in:
https://lists.openstreetmap.org/pipermail/talk-gb/2019-September/023522.html

> A possible but nasty workaround would be e.g. `bicycle=dismount_uk` representing the UK meaning of a Cyclists dismount sign.

"That is _definitely_ nasty. :) `bicycle=advisory_dismount` would be more universal."

**Comment by mvl22** [comment]
> bicycle=advisory_dismount

Personally I like this.

@systemed, can I suggest we have a video call discussion about this - as implementors of two engines, we are probably overdue to have a discussion on this general topic of mutual interest.

**Comment by systemed** [comment]
On reflection I think this is better as `bicycle:advisory=dismount`. It chimes with `maxspeed:advisory` which is [quite a popular tag](https://taginfo.openstreetmap.org/search?q=%3Aadvisory), and degrades gracefully. `bicycle=advisory_dismount` could conceivably be parsed as "unknown access option so assume no".

**Comment by mvl22** [comment]
> On reflection I think this is better as bicycle:advisory=dismount. It chimes with maxspeed:advisory which is [quite a popular tag](https://taginfo.openstreetmap.org/search?q=%3Aadvisory)

Having now seen the wiki documentation for `maxspeed:advisory`, I agree this does seem highly analogous and an optimal solution.

The key insight here is that it is not an instruction that sets a legal requirement, and is thus not really a tag in the access family (i.e. bicycle). [bicycle=...](https://wiki.openstreetmap.org/wiki/Key:bicycle) clearly defines a 'Legal restriction for cyclists'.

Use of the colon makes it a different tag while also keeping the hierarchical implication that it is a second-order matter related to the main access aspect.

> bicycle=advisory_dismount could conceivably be parsed as "unknown access option so assume no".

I agree that it would be more likely that a data consumer would parse this as an ignored option. Our own codebase would indeed do that. So yes, this would degrade gracefully.

**Comment by mvl22** [comment]
I have now posted to talk-gb on this proposal:

https://lists.openstreetmap.org/pipermail/talk-gb/2022-September/029420.html

**Comment by mvl22** [comment]
No objections so far, and only support.

So I propose:

Action:

- `ss_dismou` becomes `bicycle=yes` and `bicycle:advisory=dismount`

**Comment by mvl22** [comment]
No objections so far, and only support.

So I propose, unless clear objections start to come in:

Action:

- `ss_dismou` becomes `bicycle=yes` and `bicycle:advisory=dismount`

**Comment by systemed** [comment]
`SS_` is from the signage dataset which we don't import (and which I don't think it would be practical to import, given that there's no directionality or other geographic scope beyond the point).

The two places where we have `bicycle=dismount` are in crossings (if CRS_PEDEST is set) and restricted routes (all routes, which are additionally `highway=footway`).

Pedestrian crossings really _are_ 'bicycles dismount' so I think we leave the existing tagging there.

Restricted routes include things like the parks, which again really are 'bicycles dismount', so the existing tagging seems correct.

We don't write `bicycle=no` anywhere.

So I can't see anything we need to do here. Or am I missing something? (always very possible!)

**Comment by mvl22** [comment]
Yes, good point.

Anyway this is at least decided on if someone wants to implement the signage dataset in future, and has generated a useful tag consensus more generally.
