### ISSUE TITLE
asl_position=right/left/center

### ISSUE THREAD

**Issue by matkoniecz** [cyclestreets/tflcid-conversion#26]
Why new tag is used instead of using standard lane tagging for indicating position of cycleway lane?

Yes, lane tagging is probably not directly importable - but it is not sounding like a very important property and I think that not importing it at all is better than new tags duplicating existing lane tagging.

**Comment by mvl22** [comment]
Here are some examples from the data. Could you kindly give an example of how you would tag this situation?

Note that an ASL feeder lane is generally very short - it can even be as short as 50cm. It's often barely a "lane" at all - it's really just an indication as to which side people are expected to enter the box from.

![infrastructure (2)](https://user-images.githubusercontent.com/361423/66713911-fe1ac780-eda7-11e9-8dbd-2fea5f5f4921.jpeg)

![infrastructure](https://user-images.githubusercontent.com/361423/66713853-5bfadf80-eda7-11e9-85e1-a6caaed760bd.jpeg)

**Comment by mvl22** [comment]
Twitter user "ParisBeauAVelo" wrote at:
https://twitter.com/ParisBeauAVelo/status/1179510534447734790

"ASL entry lane is [should be] a regular cycleway:right/left=lane"

**Comment by matkoniecz** [comment]
I would not tag at all (in case of regular mapping) or map like any other bicycle lane, with cycleway=lane (though cycleway:left/cycleway:right is also perfectly fine.

**Comment by mvl22** [comment]
This is covered in #2.
