### ISSUE TITLE
Incorrect "NB In OSM bicycle=no means no bringing a bicycle at all" claim?

### ISSUE THREAD

**Issue by matkoniecz** [cyclestreets/tflcid-conversion#27]
Maybe in GB it is interpreted in this way, but in many places dismounted cyclist is considered as a pedestrian.

**Comment by mvl22** [comment]
The point is there is a separate `bicycle=dismount` tag for that.

https://wiki.openstreetmap.org/wiki/Key:access

`dismount`: "Use bicycle=dismount when people are not permitted to cycle (e.g., through a graveyard) but are allowed to dismount and bring the bike."

whereas

https://wiki.openstreetmap.org/wiki/Bicycle#Bicycle_Restrictions
has:

`bicycle=dismount`: "Where cycling is not allowed on short sections of signposted cycleroutes (typically in the UK on narrow bridges and underpasses which are shared with pedestrians), there are usually signs saying "Cyclists dismount". These have been tagged as follows (28 838+ uses as of 2014-06-05) Lower acceptance than other values, as of 2014-04-09 still not added in JOSM"

`bicycle=no`: "Where bicycles are not permitted, ensure this is indicated"

What then is the difference, if "no" actually means "dismount"?

How do you tag a shopping centre where bicycles cannot even be walked with, i.e. bicycles really are "no"?

**Comment by systemed** [comment]
@matkoniecz There is no universally agreed, explicit right to push a bicycle on a public footpath in England & Wales. Search for "usual accompaniment" if you're really interested in the legal to-and-fro.

**Comment by matkoniecz** [comment]
> What then is the difference, if "no" actually means "dismount"?

None.

> How do you tag a shopping centre where bicycles cannot even be walked with, i.e. bicycles really are "no"?

Not sure. In the ideal world it would be bicycle=no, but it is extremely widely used for places where pushing is accepted.

**Comment by b33k34** [comment]
An interesting point to note here is that the 'cyclists dismount' sign is only advisory - so there is a strong argument it shouldn't be used for routing purposes. Someone who is unable to dismount - a disabled user for example - would be at liberty to ride.

As an example, this section of pavement - item 5754465517
https://api.cyclestreets.net/v2/infrastructure.image?key=98e4ddf7f2034e46&dataset=tflcid&id=-5754465517&version=2&variant=1
is correctly signposted.  This is a signposted cycle route that goes along a section of pavement on which cycling is actually NOT permitted - hence the no-cycling sign.  The "cyclist dismount" sign has been added to reinforce the route finger post and give you more idea that you meant to proceed.  

(of course, highly confusing for any normal person arriving here)

**Comment by mvl22** [comment]
> An interesting point to note here is that the 'cyclists dismount' sign is only advisory - so there is a strong argument it shouldn't be used for routing purposes. Someone who is unable to dismount - a disabled user for example - would be at liberty to ride.

Yes, it would be generally accepted in the UK that a disabled user in that scenario is using their cycle as a mobility aid, and the Equality Act is likely to back that up.

**Comment by matkoniecz** [comment]
> Not sure. In the ideal world it would be bicycle=no, but it is extremely widely used for places where pushing is accepted.

There were some discussions in meantime and people proposed bicycle_pushed=no and bicycle_possession=no but no such tags are in real use.

Some people use `bicycle=no` and `bicycle=dismount` in attempt to distinguish this, but majority of `bicycle=no` is used in places where bicycle pushing is OK and it was always such case.

And even if that is unfortunate - it is unlikely to change and `bicycle=no` is burned for such use.

**Comment by mvl22** [comment]
> Some people use bicycle=no and bicycle=dismount in attempt to distinguish this, but majority of bicycle=no is used in places where bicycle pushing is OK and it was always such case.

I disagree. This is an ambiguous tag and the wiki, even before all your changes in various places, was contradictory on this. CycleStreets, for instance, implements what we regard as the original meaning of bicycle=no, namely no pushing either. I am well aware this whole issue has been debated _ad nauseam_ and **I don't think this ticket is the place to resurrect that debate**.

I have been intending to work for many years on an RFC, on this whole area. Briefly, in my view, the key problems are:

- There is no way to represent the UK meaning of cyclists dismount. I see bicycle=advisory_dismount has been proposed on [another ticket](https://github.com/cyclestreets/tflcid-conversion/issues/25) here and I like that.
- The issue of how to represent pushing a cycle being banned is ambiguous and the distinction between dismount/no has become disputed and murky over many years. In my view we need a new tag for this case.

In both cases I cannot see why introduction of a new tag would be a problem. These would not conflict with existing usage, and would be something that people can start to use. Perhaps in a decade or so people would have moved existing cases to these :)

As I say, I will post to talk-gb on this in due course.

@systemed, can I suggest we have a video call discussion about this - as implementors of two engines, we are probably overdue to have a discussion on this general topic of mutual interest.

There is a [separate ticket](https://github.com/cyclestreets/tflcid-conversion/issues/25) on the problem of the UK Cyclists Dismount, so discussion about that should be there.

I intend to close this ticket, as it is not actually about implementation of the CID conversion.

**Comment by matkoniecz** [comment]
> I have been intending to work for many years on an RFC, on this whole area

I would be happy to participate in it, if it would happen

> original meaning of bicycle=no, namely no pushing either

Then how "pushing allowed, cycling not allowed" was tagged before `bicycle=dismount` started to be used?

**Comment by systemed** [comment]
Closing as not a CID issue.
