### ISSUE TITLE
Unclear "TRUE: highway=cycleway, cycleway=track"

### ISSUE THREAD

**Issue by matkoniecz** [cyclestreets/tflcid-conversion#28]
"TRUE: highway=cycleway, cycleway=track" means "either highway=cycleway on a separate line or cycleway=track on road", not "highway=cycleway, cycleway=track" on one object, right?

**Comment by mvl22** [comment]
No.

The two asset types to which this applies are:

https://bikedata.cyclestreets.net/tflcid/conversion/#clt_bbypas
Continuous Cycle Facilities at Bus Stop - clt_bbypas

https://bikedata.cyclestreets.net/tflcid/conversion/#sig_gate
Cycle/Bus Gate - sig_gate

In both cases, these are unambiguously separate from the main part of the road, so are drawn as a separate way.

Accordingly, there would be road (as normal) and then a separate way for the cycleway, tagged as:
`highway=cycleway, cycleway=track`
i.e. a cycleway whose specific type is track.

**Comment by matkoniecz** [comment]
Whooops. So this tag combination had reasonable meaning and it is not just result of a Potlatch bug.

Sadly it was not documented and I missed it and it was missed by commenters at https://help.openstreetmap.org/questions/65366/highwaycycleway-cyclewaytrack

See https://wiki.openstreetmap.org/wiki/Tag:cycleway%3Dtrack - JOSM validator now encourages to be remove this tagging.

Still, double meaning of cycleway=track seems a bit unfortunate.
