### ISSUE TITLE
Add link to TfL's guide

### ISSUE THREAD

**Issue by RobJN** [cyclestreets/tflcid-conversion#3]
Can you add a link to [TfL's guide](https://cycling.data.tfl.gov.uk/CyclingInfrastructure/documentation/asset_information_guide.pdf) to your [conversion webpage](https://bikedata.cyclestreets.net/tflcid/conversion/) please. It will help with reviewing the detail.

**Comment by RobJN** [comment]
I see now that you have actually split this up in to the relevant sections. Probably ok to close this issue but may be nice to put a link to the full document at the top...(?).

**Comment by mvl22** [comment]
Good suggestion, thanks! Now added.

https://bikedata.cyclestreets.net/tflcid/conversion/
