### ISSUE TITLE
oneway:bicycle=no missing for clt_contra

### ISSUE THREAD

**Issue by matkoniecz** [cyclestreets/tflcid-conversion#33]
`TRUE: If clt_mandat=TRUE THEN cycleway=opposite_lane, oneway=yes ELSE cycleway=opposite, oneway=yes`

`oneway:bicycle` tag appears to be missing

**Comment by mvl22** [comment]
> TRUE: If clt_mandat=TRUE THEN cycleway=opposite_lane, oneway=yes ELSE cycleway=opposite, oneway=yes

NB You meant:

If `clt_contra=TRUE` ...

**Comment by mvl22** [comment]
> oneway:bicycle tag appears to be missing

This was implemented at:
https://github.com/cyclestreets/tflcid-conversion/blob/master/readers/clt_roads.rb#L116-L119
