### ISSUE TITLE
please do not spam useless fixme tags

### ISSUE THREAD

**Issue by matkoniecz** [cyclestreets/tflcid-conversion#36]
I noticed in dataset linked on mailing lists  that adding `fixme=Check bike parking type` to every single bicycle parking without tagged `bicycle_parking` is planned

is not needed - just lack of bicycle_parking tag is enough to note that, and will be spotted by tools such as StreetComplete

(spotted on id RWG102691)

**Comment by mvl22** [comment]
Agreed.

It is indeed quite ordinary for the cycle parking type not to be known or stated. So there should be no type or fixme given.

@systemed The change I think is presumably at this point:

https://github.com/cyclestreets/tflcid-conversion/blob/master/readers/parking.rb#L96

**Comment by systemed** [comment]
#worksforme
