### ISSUE TITLE
Make import edit summary and attribution clearer

### ISSUE THREAD

**Issue by ghost** [cyclestreets/tflcid-conversion#40]
[The import](https://www.openstreetmap.org/changeset/121097200) seems to have an erroneous edit summary, and isn't very clear. To add, the importing user has no information. Considering most mappers aren't on the talk-gb-london mailing list, it would make sense to change the summary to something like "Importing cycling infrastructure in London from TfL CID. For more information, see https://lists.openstreetmap.org/pipermail/talk-gb-london/2022-May/000210.html", and adding a notice to the page of the importing user that they are using the account for importing, and optionally, who they work for.

**Comment by matkoniecz** [comment]
> optionally, who they work for

If they are paid for editing, or edit based on instructions received from someone else - it is not optional to document this. See https://wiki.osmfoundation.org/wiki/Organised_Editing_Guidelines

**Comment by mvl22** [comment]
> If they are paid for editing, or edit based on instructions received from someone else - it is not optional to document this. 

They have documented the users at:
https://wiki.openstreetmap.org/wiki/TfL_Cycling_Infrastructure_Database#Changeset_Tags

**Comment by matkoniecz** [comment]
Are https://www.openstreetmap.org/user/luxiaghd and https://www.openstreetmap.org/user/AyushS183 accounts used by employees or people editing as instructed? Then 

> user’s profile page should also include links to the wiki pages of the organised edits and organisations they participate in on an ongoing basis. 

from https://wiki.osmfoundation.org/wiki/Organised_Editing_Guidelines is not fulfilled

**Comment by mvl22** [comment]
I have given the project team a set of guidance for good practice with changesets, as well as reminding them of the need for the profile page statement. This covers areas like:

- Use small geographical area
- Descriptions should be self-explanatory
- Use a hashtag and link to the wiki page about the project
- Avoid mixing different asset types, which is already being done
- Reference involvement on each person's profile page
- Make sure people understand the tags, or do more training
- Apply common sense given that the data has aged, especially with cycle lanes/tracks
  - E.g. if CID has lane and current data shows track created newly, then CID is clearly old
- Use History to get a clearer understanding of the area
- If errors are made, it is expected that they will be cleared up

**Comment by mvl22** [comment]
Further to the [follow-up posting](https://lists.openstreetmap.org/pipermail/imports/2022-August/006937.html) by @matkoniecz, on the imports list, I see the pages at:

- https://www.openstreetmap.org/user/luxiaghd
- https://www.openstreetmap.org/user/AyushS183

now comply with the organised editing guidelines requirement to state involvement.
