### ISSUE TITLE
Addition of ref:GB:tflcid ID

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/tflcid-conversion#41]
On https://lists.openstreetmap.org/pipermail/talk-gb-london/2022-June/000217.html, Robert Skedgell usefully noted:

> 5) Importing TfL's unique asset ID might have been useful. Where I have matched assets with imagery (mostly in Newham), I have used ref:GB:tflcid=*. The URLs of the asset photographs can be derived from these IDs, which could perhaps be useful for navigation apps.

This seems sensible.

Is is also asked by Robert here:
https://lists.openstreetmap.org/pipermail/imports/2022-June/006882.html

I see at [one point in the code](https://github.com/cyclestreets/tflcid-conversion/blob/master/readers/traffic_calming_sideroads.rb#L26) at least we are using `tfl_id`.

@systemed Presumably this could be added in many other places. What is the feasibility of doing this in a consistent way, e.g. at top-level somehow rather than scattered in every tag write through the code?

@systemed Action so far is:

- Change `tfl_id` to `ref:GB:tflcid`.
- Look into feasibility of adding this more consistently throughout.

**Comment by systemed** [comment]
Technically not too difficult! I think the bigger question is whether we want third party IDs in OSM - historically it’s not really been popular. Maybe a separate browsable map would help?

**Comment by mvl22** [comment]
> Maybe a separate browsable map would help? 

There is obviously the map, which contains the IDs, at:
https://bikedata.cyclestreets.net/tflcid/

**Comment by mvl22** [comment]
Raised on talk-gb at:
https://lists.openstreetmap.org/pipermail/talk-gb/2022-August/029245.html

**Comment by mvl22** [comment]
There has been only one response, with mild support at that:

https://lists.openstreetmap.org/pipermail/talk-gb/2022-August/029247.html

I suggest we simply do the one action outlined above, namely this, so that at least the existing data is correct.

- Change `tfl_id` to `ref:GB:tflcid`.

If there is a sudden outpouring of demand for this tagging more widely, we can reassess.

**Comment by systemed** [comment]
Currently we write the TfL ID in the `tiger:upload_uuid` tag, which means it's visible in editors but is automatically stripped before upload. Is the change therefore to replace `tiger:upload_uuid` with `ref:GB:tflcid`, which means it will be uploaded to OSM?

(FWIW I'm not a fan of tags that encode geometry like 'GB' into the key or value - OSM is a spatial database, we don't additionally need the tags to say that it's in GB. But I'm not that fussed about it!)

**Comment by mvl22** [comment]
The suggestion was that `ref:GB:tflcid=*` be added more widely in the converted dataset to all kinds of assets. However, it is clear from the mailing list response this is not a widely-held view, or at least it hasn't been expressed as such.

I think if the `tfl_id` isn't coming through in the result, I had misunderstood [that part](https://github.com/cyclestreets/tflcid-conversion/blob/master/readers/traffic_calming_sideroads.rb#L26) of the code.

Accordingly, I'll close this issue as I don't think any further action is needed.
