### ISSUE TITLE
use incline=up/down if provided by data

### ISSUE THREAD

**Issue by matkoniecz** [cyclestreets/tflcid-conversion#42]
https://bikedata.cyclestreets.net/tflcid/conversion/#rst_steps claims that it is not useful to add it - but in reality any claims that it is implied by way directionality is not matching reality

see https://taginfo.openstreetmap.org/tags/highway%3Dsteps#combinations - it is 20% and 12%

See http://taghistory.raifer.tech/#***/incline/up&***/incline/down which also indicates that where it was not tagged then also data collected via StreetComplete are not overwhelmingly one of this values

**Comment by mvl22** [comment]
The [wiki](https://wiki.openstreetmap.org/wiki/Tag:highway=steps) says

> If known, use the tag incline=up — when the direction of the way points upwards — or the tag incline=down, respectively.

though the examples don't even bother to use it. I remain of the view this is not a particularly useful tag - we know there are steps.

> but in reality any claims that it is implied by way directionality is not matching reality

Yes, sorry, that is correct.

Anyway, we can't implement this as the CID data doesn't say about the incline. It just says there are steps.

So I don't think any action on incline can be taken here.

This CID attribute is part of the Restricted routes set, which Richard has produced a helpful [clarification note](https://github.com/cyclestreets/tflcid-conversion/blob/master/readers/restricted_routes.md) on. It points out the need for manual consideration here.

However, investigation from this discussion shows that currently we don't actually process the steps tag at all, looking at the [reader](https://github.com/cyclestreets/tflcid-conversion/blob/master/readers/restricted_routes.rb) implementation.

I will cover that in #46.

**Comment by matkoniecz** [comment]
And maybe also remove (most of) "OSM comment" field?

>  I remain of the view this is not a particularly useful tag - we know there are steps, and the way has a direction so we automatically know there is an incline.

Ideally, routing would give greater penalty for carrying bicycle up than for carrying it down the steps (no idea is anything bothering to make such tuning)

**Comment by mvl22** [comment]
> And maybe also remove (most of) "OSM comment" field?

I'm not planning to maintain the page at:
https://bikedata.cyclestreets.net/tflcid/conversion/

as it reflects a proposal.

If someone else wants to spend a lot of time updating it, by transposing everything from the tickets into the JSON file, they are welcome to submit pull requests. The code shows the final implementation, and that forms documentation in its own right.

> Ideally, routing would give greater penalty for carrying bicycle up than for carrying it down the steps (no idea is anything bothering to make such tuning)

Indeed. Gosh really was not thinking clearly this morning on this issue... Steps are of course a total pain in either direction anyway...
