### ISSUE TITLE
walk=yes -> foot=yes

### ISSUE THREAD

**Issue by matkoniecz** [cyclestreets/tflcid-conversion#44]
https://bikedata.cyclestreets.net/tflcid/conversion/#trf_barier

> TRUE: barrier=bollard, access=no, bicycle=yes, walk=yes

Also, is blocking horses and motorcycles intentional?

**Comment by matkoniecz** [comment]
BTW, is #13 not deployed or is there desync between docs and code?

**Comment by mvl22** [comment]
> Also, is blocking horses and motorcycles intentional?

No, but there is no data either way. If OSM already has information on horses/motorcycles then the merging process would retain that.

The vast majority of bollard cases I've seen currently have:

```
access = no
barrier = bollard
bicycle = yes
foot = yes
```

so your question really is a more general one.

**Comment by mvl22** [comment]
> BTW, is https://github.com/cyclestreets/tflcid-conversion/pull/13 not deployed or is there desync between docs and code?

The documentation page is not run directly off that JSON page but comes from an API coming from a database.

I've now transposed the [changes to the JSON file](https://github.com/cyclestreets/tflcid-conversion/commits/master/schema/schema.json) into the database. I'll try and remember to do these if there are further changes to the JSON, though it's a tedious task.
