### ISSUE TITLE
No Vehicles -> access=no, bicycle=yes

### ISSUE THREAD

**Issue by matkoniecz** [cyclestreets/tflcid-conversion#45]
Should it be maybe `vehicle=no` on ways where pedestrians are allowed?

https://bikedata.cyclestreets.net/tflcid/conversion/#ss_noveh

**Comment by mvl22** [comment]
Fixed in a396026309b871f967f76ce5574c36bc3463076b - `foot=yes` was missing.

However, the signage data is not being conflated into OSM anyway.
