### ISSUE TITLE
bridges may be partially steps

### ISSUE THREAD

**Issue by matkoniecz** [cyclestreets/tflcid-conversion#46]
see https://bikedata.cyclestreets.net/tflcid/conversion/#res_bridge

> TRUE: highway=footway, bridge=yes, layer=1, bicycle=dismount

![RWG276596](https://user-images.githubusercontent.com/899988/182944948-deb8eb5e-5e54-4132-b5c8-c4fe6afe3fb6.jpg)

it would be better to map step sections as `highway=steps` not `highway=footway`

the same goes for https://bikedata.cyclestreets.net/tflcid/conversion/#res_tunnel where applicable

**Comment by mvl22** [comment]
Investigation from the discussion in #42 shows that we don't actually convert the steps tag yet, looking at the [reader](https://github.com/cyclestreets/tflcid-conversion/blob/master/readers/restricted_routes.rb) implementation.

Action @systemed:

- If `res_steps=TRUE` then set `highway=steps` as per #46.
- If `res_tunnel=TRUE` then set tunnel=yes.
