### ISSUE TITLE
Is it possible to raise a warning where a conflated node is attached to a building?

### ISSUE THREAD

**Issue by rskedgell** [cyclestreets/tflcid-conversion#48]
This is likely to be an error for any TfLCID asset except wall-mounted cycle parking.

See https://osmcha.org/changesets/130428777/ particularly n10282561705, n10282561589, n10282549089

**Comment by EdWhittakerSweco** [comment]
Yes, definitely an error especially for traffic calming features.

I've done an analysis in QGIS with Overpass and identified all traffic calming nodes not attached to a highway way and out of about 25,000 recently conflated, found 65 that meet this criteria and we will need to fix. This includes the ones you've also identified

The other issues you've identified is where our conflation has introduced kinks into the road network. I'll need to confirm with the person who did this work when they get back to work next week though it does look like we hadn't kept our JOSM cached OSM data up to date and our node positions are in-line with the old centrelines. This looks like a limited extent and we can work through and fix manually where kinks are visible.

We've almost conflated all of this particular CID feature though will look at improving our processes moving forwards to warn of these issues


Nodes not attached to highways -
10282549089, 9599756999, 10282554685, 10282561741, 10282561608, 9599757003, 10282528211, 10282549100, 10282549101, 10282561750, 10282554701, 10279041298, 10282561686, 10282506894, 10282561536, 10282561757, 10273620214, 10282561694, 10282506907, 10282561630, 10282561632, 10282554719, 10282561766, 10273616808, 10273620224, 10273620225, 10282549055, 9754764551, 10282554726, 10282561705, 10273185911, 10273620228, 10282549058, 10273620210, 10282561707, 10273620232, 10273185916, 10282554737, 10282561558, 8488977741, 8488977742, 10282554743, 10273185924, 10282561584, 10282561718, 10273185925, 10282561566, 10282554750, 10273185929, 10282561589, 10282549077, 10282554667, 10282561590, 10282561725, 9597526559, 10282554754, 10282561726, 10282554670, 10273620250, 10273620251, 10273620252, 10282561598, 10282561665, 9597526566, 10282561667

**Comment by rskedgell** [comment]
<blockquote>We've almost conflated all of this particular CID feature though will look at improving our processes moving forwards to warn of these issues</blockquote>

Really? Why do I keep finding so many missing, misplaced, incorrectly tagged and duplicated traffic_calming=* nodes, over 6 months after the project was quietly abandoned?
