### ISSUE TITLE
duplicate in the TFL Database

### ISSUE THREAD

**Issue by hb0nd** [cyclestreets/tflcid-conversion#49]
There seems to be a duplicate in the TFL database, both `RWG196306` and `RWG194775` refer to the same feature
https://www.osm.org/node/10282431206
https://www.osm.org/node/10282507922

it'd be good if this was fixed in the TFL database, then OSM was updated with the correct ID :)

**Comment by mvl22** [comment]
Reviewing the images at
https://bikedata.cyclestreets.net/tflcid/#18.27/51.453634/0.042233

this does seem to be the case.

**Comment by luxiaruc** [comment]
Duplicate fixed.
