### ISSUE TITLE
Signal-Controlled Crossing (crs_signal) implies bicycle=yes

### ISSUE THREAD

**Issue by RobJN** [cyclestreets/tflcid-conversion#5]
TfL's use of Signal-Controlled Crossing (crs_signal) seems to imply bicycle=yes. This should therefore be added to the node on all instances (TRUE and FALSE).

**Comment by mvl22** [comment]
> TfL's use of Signal-Controlled Crossing (crs_signal) seems to imply bicycle=yes. This should therefore be added to the node on all instances (TRUE and FALSE).

I don't think this is actually correct. Perhaps oddly for a 'Cycling' Infrastructure Database, things like zebra crossings are present, which are not legally permissible to cycle over, though in practice these are sometimes useful links when dismounted. You can see that one of the fields is for 'Pedestrian-Only Crossing' (`CRS_PEDEST`).

However I think your main point is correct, namely that we should be adding `bicycle=yes` to the main `highway=crossing` when it is not pedestrian-only.

@systemed Action here is to change this line:
`if attrs['CRS_PEDEST'] then osm_tags['bicycle']="dismount" end`
to add an else clause, such that if `CRS_PEDEST=FALSE` then `bicycle=yes`.

**Comment by mvl22** [comment]
> TfL's use of Signal-Controlled Crossing (crs_signal) seems to imply bicycle=yes. This should therefore be added to the node on all instances (TRUE and FALSE).

I don't think this is actually correct. Perhaps oddly for a 'Cycling' Infrastructure Database, things like zebra crossings are present, which are not legally permissible to cycle over, though in practice these are sometimes useful links when dismounted. You can see that one of the fields is for 'Pedestrian-Only Crossing' (`CRS_PEDEST`).

However I think your main point is correct, namely that we should be adding `bicycle=yes` to the main `highway=crossing` when it is not pedestrian-only.

@systemed Action here is to change this line:
`if attrs['CRS_PEDEST'] then osm_tags['bicycle']="dismount" end`
to add an else clause, such that if `CRS_PEDEST=FALSE` then `bicycle=yes`.
