### ISSUE TITLE
Signal-Controlled Crossing (crs_signal) proposal conflicts existing tags

### ISSUE THREAD

**Issue by RobJN** [cyclestreets/tflcid-conversion#6]
In Signal-Controlled Crossing (crs_signal) you are proposing:

- TRUE: crossing=traffic_signals 
- FALSE: crossing=uncontrolled

On conflation this risks replacing existing more detailed data such as crossing=toucan.

There are two options:

1. Add a comment saying that on conflation users should not amend cases where OSM already has more detail. OR
2. Propose moving the detail to the crossing_ref=* tag.

A quick check on tag info shows that crossing_ref=toucan is now used over twice as much as crossing=toucan. Similar for zebra, etc, etc. My preference is for the later (option 2).

**Comment by mvl22** [comment]
> On conflation this risks replacing existing more detailed data such as crossing=toucan.

Yes, I agree there is a potential danger here.
 
> A quick check on tag info shows that crossing_ref=toucan is now used over twice as much as crossing=toucan.

Yes, crossing_ref is now at [14,834 instances](https://taginfo.openstreetmap.org/tags/crossing_ref=toucan#overview) but [crossing=toucan](https://taginfo.openstreetmap.org/tags/crossing=toucan#overview) is at 3,606, though actually only twenty cases in London, which could easily be cleaned up. [crossing=toucan](https://wiki.openstreetmap.org/wiki/Key:crossing) seems to be deprecated as per the wiki, and the correct usage is indeed [crossing_ref=toucan](https://wiki.openstreetmap.org/wiki/Key:crossing_ref). Nonetheless, we are where we are. In any cases, there could be other values, not just toucan.

Currently [the code shows](https://github.com/cyclestreets/tflcid-conversion/blob/master/readers/crossings.rb#L30-L41) that we do not do a match on existing data and get current tags. I suspect it would be almost impossible to get a reliable matching mechanism given that a junction will have all kinds of crossing ways/nodes present.

> 1. Add a comment saying that on conflation users should not amend cases where OSM already has more detail. OR
> 2. Propose moving the detail to the crossing_ref=* tag.

We can't actually do the second, as [the spec shows](https://bikedata.cyclestreets.net/tflcid/conversion/#crs_signal) there is no further information on the type of crossing.

So I think the current code implementation is correct as it is, and so:

**Action** is to ensure that operatives doing the merging are made aware that `crossing=traffic_signals/uncontrolled` should not replace more specific animal-named crossing type, e.g. zebra/toucan/zebra/pelican/puffin.

**Comment by mvl22** [comment]
> Action is to ensure that operatives doing the merging are made aware that crossing=traffic_signals/uncontrolled should not replace more specific animal-named crossing type, e.g. zebra/toucan/zebra/pelican/puffin.

I have now relayed this to the project team, asking them to add it to the procedural documentation, so am closing this call.
